# Generated by Django 6.0.1 on 2026-01-14 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Employee's full name", max_length=200)),
                ('email', models.CharField(help_text='Email Address', unique=True, validators=[django.core.validators.EmailValidator()])),
                ('department', models.CharField(blank=True, help_text="Job Department (e.g., 'HR', 'Engineering', 'Sales')", max_length=100, null=True)),
                ('role', models.CharField(blank=True, help_text="Job Role(e.g., 'Manager', 'Developer','Analyst')", max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True, help_text='Date when an employee was added')),
            ],
        ),
    ]
