# Generated by Django 6.0.1 on 2026-01-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('HR', 'Hr'), ('Engineering', 'Engineering'), ('Sales', 'Sales'), ('Finance', 'Finance'), ('Opeartion', 'Operation')], help_text="Job Department (e.g., 'HR', 'Engineering', 'Sales')", max_length=100, null=True),
        ),
    ]
